name: Build and Push to ACR

on:
  push:
    branches:
      - main
    paths:
      - 'Azure-Practices/AzureServiceBus/ShoppingMicroServices/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - OrderService/OrderService
          - PaymentService/PaymentService
          - ShippingService/ShippingService
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: az acr login --name ${{ secrets.ACR_NAME }}
    - run: |
        cd Azure-Practices/AzureServiceBus/ShoppingMicroServices/${{ matrix.service }}
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:v1 .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:v1
