name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  orderservice:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: az acr login --name ${{ secrets.ACR_NAME }}
    - run: |
        cd Azure-Practices/AzureServiceBus/ShoppingMicroServices/OrderService/OrderService
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/orderapi:v1 .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/orderapi:v1
    # Only run if OrderService files changed
    if: contains(join(github.event.commits.*.modified), 'OrderService')

  paymentservice:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: az acr login --name ${{ secrets.ACR_NAME }}
    - run: |
        cd Azure-Practices/AzureServiceBus/ShoppingMicroServices/PaymentService/PaymentService
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/paymentapi:v1 .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/paymentapi:v1
    if: contains(join(github.event.commits.*.modified), 'PaymentService')

  shippingservice:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: az acr login --name ${{ secrets.ACR_NAME }}
    - run: |
        cd Azure-Practices/AzureServiceBus/ShoppingMicroServices/ShippingService/ShippingService
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/shippingapi:v1 .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/shippingapi:v1
    if: contains(join(github.event.commits.*.modified), 'ShippingService')
