name: Build and Push to ACR for Azure Event Hub Bus POC.

on:
  push:
    branches:
      - main

jobs:
  orderservice:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: az acr login --name ${{ secrets.ACR_NAME }}
    - run: |
        cd Azure-Practices/AzureEventHub/ShippingLogisticsPOC/OrderService/OrderService
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/orderservice:v1 .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/orderservice:v1

  paymentservice:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: az acr login --name ${{ secrets.ACR_NAME }}
    - run: |
        cd Azure-Practices/AzureEventHub/ShippingLogisticsPOC/PaymentService/PaymentService
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/paymentservice:v1 .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/paymentservice:v1

  shippingservice:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: az acr login --name ${{ secrets.ACR_NAME }}
    - run: |
        cd Azure-Practices/AzureEventHub/ShippingLogisticsPOC/ShippingService/ShippingService
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/shippingservice:v1 .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/shippingservice:v1
